############################################################
## Variables:                                              #
##                                                         #
## DEPLOY_TRAVIS ------> 1 para activar releases           #
## USER_TRAVIS --------> usuario de github                 #
## EMAIL_TRAVIS -------> email de github                   #
## MILESTONE_TRAVIS ---> nÃºmero de milestone               #
## NOMBRE_ZIP ---------> decide                            #
## RAMA_TRAVIS --------> master                            #
## TOKEN_TRAVIS -------> token personal sin encriptar      #
############################################################

language: python

python:
  - 3.6

sudo: required

dist: xenial

services:
  - postgresql

addons:
  - postgresql: "9.4"

before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"

install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install flake8

script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - flake8 --select E501,E265 . --exit-zero
#  - python ./decide/manage.py makemigrations
#  - python ./decide/manage.py migrate
#  - python ./decide/manage.py compilemessages
  - python ./manage.py test --keepdb
  - if [[ $TRAVIS_BRANCH == $RAMA_TRAVIS ]] && [[ $DEPLOY_TRAVIS == "1" ]]; then git archive --format zip --output ./$NOMBRE_ZIP.zip $RAMA_TRAVIS; echo "Zip generado correctamente."; fi
  - cp travis_local_settings.py local_settings.py
  - cp ./decide/travis_settings.py ./decide/settings.py

before_deploy:
  - git config --local user.name $USER_TRAVIS
  - git config --local user.email $EMAIL_TRAVIS
  - export YEAR=`date +"%Y"`  
  - export GIT_TAG=M$MILESTONE_TRAVIS-build.$TRAVIS_BUILD_NUMBER-$YEAR
  - git tag -a $GIT_TAG -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"

deploy:
  - provider: heroku
    app: $HEROKU_APP_NAME
    strategy: git
    api_key:
      secure: $HEROKU_API_KEY
   
after_deploy:
  - provider: releases
    api-key:
      secure: $TOKEN_TRAVIS
    file: "./$NOMBRE_ZIP.zip"
    skip_cleanup: true
    on:
      branch: $RAMA_TRAVIS
      condition: $DEPLOY_TRAVIS = 1
      tags: false

notifications:
  email: false